version: "3"

services:
  app:
    image: tuannguyensn2001/athena
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"  # Bind the port from .env
    restart: always
    env_file:
      - .env