version: "3"

services:
  app:
    container_name: athena-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "15000:15000"
    restart: always
    env_file:
      - .env
