version: "3"

services:
  app:
    container_name: athena-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"  # Bind the port from .env
    restart: always
    env_file:
      - .env