apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-athena
spec:
  replicas: 1
  selector:
    matchLabels:
      app: athena
  template:
    metadata:
      name: pod-athena
      labels:
        app: athena
    spec:
      containers:
        - name: athena
          image: tuannguyensn2001/athena:latest
          imagePullPolicy: Always
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: config-athena
                  key: PORT
            - name: GIN_MODE
              valueFrom:
                configMapKeyRef:
                  name: config-athena
                  key: GIN_MODE
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: DATABASE_URL
                  name: secret-athena
          ports:
            - containerPort: 15000
              protocol: TCP
