name: Athena Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  PORT: ${{ vars.PORT }}

jobs:
  migrate:
    name: Run migrations
    runs-on: ubuntu-latest

    steps:
      - name: show env
        run: echo "my env is  $PORT"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Install golang-migrate
        run: go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

      - name: Run migrate
        run: migrate --path migrations --database postgres://tuannguyensn2001:lYIcxWPF0i4t@ep-cold-sound-41447706.ap-southeast-1.aws.neon.tech/neondb?options=endpoint%3Dep-cold-sound-41447706 up
