name: Athena Pipeline



on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  VERSION: 1.21


jobs:
  test:
    name: Run test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.VERSION }}
      - name: Install dependencies
        run: go mod download
      - name: Run tests
        run: go test ./...

  migrate:
    environment: staging
    name: Run migrations
    runs-on: ubuntu-latest
    needs: test
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.VERSION }}

      - name: Install golang-migrate
        run: go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

      - name: Run migrate
        run: migrate --path migrations --database $DATABASE_URL up

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test
    environment: staging
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup docker
        uses: docker/setup-buildx-action@v1
      - name: build and push
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker buildx build -t $DOCKER_USERNAME/athena_service:latest --push .
          docker logout