name: Athena Pipeline



on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  VERSION: 1.21


jobs:
  test:
    name: Run test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.VERSION }}
      - name: Install dependencies
        run: go mod download
      - name: Run tests
        run: go test ./...

  migrate:
    environment: staging
    name: Run migrations
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.VERSION }}

      - name: Install golang-migrate
        run: go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

      - name: Run migrate
        run: migrate --path migrations --database $DATABASE_URL up
